# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
matrix:
  include:
    - os: linux
      julia: 0.6
      env: TESTCMD="xvfb-run julia"
    - os: linux
      julia: nightly
      env: TESTCMD="xvfb-run julia"
    - os: osx
      julia: 0.6
      env: TESTCMD="julia"
    - os: osx
      julia: nightly
      env: TESTCMD="julia"
  allow_failures:
    - julia: nightly
branches:
  only:
    - master
    - /^v[0-9]+\.[0-9]+\.[0-9]+$/ # version tags
notifications:
  email: false
before_script:
  - julia -e 'Pkg.clone("https://github.com/JuliaRobotics/RigidBodySim.jl")'
  - julia -e 'Pkg.clone("https://github.com/tkoolen/SimpleQP.jl")'
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - $TESTCMD -e 'Pkg.clone(pwd()); Pkg.build("QPControl"); Pkg.test("QPControl"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("QPControl")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
