# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.1
  - nightly
matrix:
  allow_failures:
  - julia: nightly
branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/ # version tags
notifications:
  email: false
after_success:
  - julia -e 'using Pkg; pkg"add Coverage"; using Coverage; Codecov.submit(process_folder())'
