name = "QPControl"
uuid = "d1d18edd-2826-5709-814b-0b0c7d0d034b"
authors = ["Twan Koolen <koolen.twan@gmail.com>", "Robin Deits <robin.deits@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
Parametron = "41fac6d6-0ffa-5bcc-b863-17dd4947be41"
RigidBodyDynamics = "366cf18f-59d5-5db9-a4de-86a9f6786172"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StaticUnivariatePolynomials = "6f584044-cad5-5b68-a429-1e244a824f76"

[compat]
MathOptInterface = "0.8"
Parametron = "0.9"
RigidBodyDynamics = "2"
Rotations = "0.9, 0.10, 0.11, 0.13"
StaticArrays = "0.10, 0.11, 0.12"
StaticUnivariatePolynomials = "0.6"
julia = "1.2, 1.3"

[extras]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[targets]
test = ["Pkg"]
